"""
src/a6_bibliometric_table.py
============================
Analysis Module 6: Main Bibliometric Information Table
------------------------------------------------------
Produces Table: Comparative bibliometric metrics per technology category
Corresponds to: Manuscript Table 1 (main bibliometric information)

Output files (saved to results/):
  - table_A6_bibliometric_main.csv   → main bibliometric table (CSV)
  - table_A6_bibliometric_main.md    → markdown-formatted table

Metrics computed per category:
  - Documents (N)
  - Total Citations (TC)
  - H-index
  - Annual Growth Rate % (CAGR)
  - Average Citations per Document (AC)
  - Cited Publications (NCP)
  - % Cited Publications
  - Citations per Cited Document (CCP)
  - Earliest Year (first article)
  - Most Productive Year
"""

from __future__ import annotations
import sys
import math
from pathlib import Path

import pandas as pd
import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent))

from utils.classifier import CATEGORY_ORDER
from utils.plot_style import apply_global_style


REF_YEAR = 2026  # Reference year for age-based citation calculations


def _h_index(citations: list[float]) -> int:
    cites = sorted([int(c) for c in citations], reverse=True)
    h = 0
    for i, c in enumerate(cites):
        if c >= i + 1:
            h = i + 1
        else:
            break
    return h


def _compute_metrics(df_subset: pd.DataFrame, col_cit: str, col_year: str) -> dict:
    """Compute all bibliometric metrics for a subset."""
    if df_subset.empty:
        return {m: "N/A" for m in [
            "Documents (N)", "Total Citations (TC)", "H-index",
            "Annual Growth Rate %", "Avg Citations/Doc (AC)", "Cited Pubs (NCP)",
            "% Cited", "Cit/Cited Doc (CCP)", "First Year", "Peak Year",
        ]}

    df = df_subset.copy()
    df[col_cit] = pd.to_numeric(df[col_cit], errors="coerce").fillna(0)
    df[col_year] = pd.to_numeric(df[col_year], errors="coerce")
    df = df.dropna(subset=[col_year])

    n = len(df)
    tc = int(df[col_cit].sum())
    h = _h_index(df[col_cit].tolist())
    ac = round(tc / n, 2) if n > 0 else 0

    cited = df[df[col_cit] > 0]
    ncp = len(cited)
    pct_cited = round(100 * ncp / n, 1) if n > 0 else 0
    ccp = round(tc / ncp, 2) if ncp > 0 else 0

    min_year = int(df[col_year].min())
    max_year = int(df[col_year].max())
    time_span = max_year - min_year

    first_count = len(df[df[col_year] == min_year])
    last_count = len(df[df[col_year] == max_year])
    if first_count > 0 and time_span > 0:
        cagr = round((math.pow(last_count / first_count, 1 / time_span) - 1) * 100, 2)
    else:
        cagr = 0.0

    peak_year = int(df.groupby(col_year).size().idxmax())

    return {
        "Documents (N)": n,
        "Total Citations (TC)": tc,
        "H-index": h,
        "Annual Growth Rate %": cagr,
        "Avg Citations/Doc (AC)": ac,
        "Cited Pubs (NCP)": ncp,
        "% Cited": f"{pct_cited}%",
        "Cit/Cited Doc (CCP)": ccp,
        "First Year": min_year,
        "Peak Year": peak_year,
    }


# ---------------------------------------------------------------------------
def run(df: pd.DataFrame, results_dir: Path) -> None:
    """
    Execute Main Bibliometric Information Table generation.

    Parameters
    ----------
    df : pd.DataFrame
        Cleaned and classified DataFrame.
    results_dir : Path
        Output directory.
    """
    print("\n[A6] Main Bibliometric Information Table")
    print("-" * 50)

    results_dir.mkdir(parents=True, exist_ok=True)

    col_cit = "Cited by" if "Cited by" in df.columns else "Citations"
    col_year = "Year"

    table: dict[str, dict] = {}

    # Full corpus
    table["Full Corpus"] = _compute_metrics(df[df["Tech_Category"].notna()], col_cit, col_year)

    # Per category
    for cat in CATEGORY_ORDER:
        df_cat = df[df["Tech_Category"] == cat]
        table[cat] = _compute_metrics(df_cat, col_cit, col_year)

    # Build DataFrame
    df_table = pd.DataFrame(table).T
    df_table.index.name = "Category"

    # CSV
    df_table.to_csv(results_dir / "table_A6_bibliometric_main.csv")
    print(f"  → Saved: {results_dir / 'table_A6_bibliometric_main.csv'}")

    # Markdown
    md_lines = ["# Main Bibliometric Information\n\n"]
    md_lines.append(df_table.to_markdown())
    md_lines.append("\n\n> Generated by a6_bibliometric_table.py using canonical classifier (utils/classifier.py)\n")
    (results_dir / "table_A6_bibliometric_main.md").write_text("\n".join(md_lines), encoding="utf-8")
    print(f"  → Saved: {results_dir / 'table_A6_bibliometric_main.md'}")

    # Print summary
    print("\n" + df_table.to_string())
    print("[A6] Done.")
